[hooks]
pre-commit = "cargo fmt --all"
pre-push = "cargo nextest run --no-capture && cargo deny check && cargo clippy --all-targets --all-features -- -D warnings && cargo fmt --all -- --check"

[logging]
verbose = true
